language: node_js

node_js:
  - "0.12"

before_install:
  - npm install -g grunt-cli

install:
  - npm install
  - npm run build
  - npm test

env:
  global:
    - secure: hE76XayVUowzrfgElQZqT1d+WrRGqqnfYItUOmreVB/iFK9Y4YJJdj4/n2HLvcf5hrSXbG4jK/mDLTfeRyWabv5vuS41er15wAv9CJ2HjnGLGCrRP6zyZbaLw4lWwtABy7ozDB5xchmWtrcHrVdaT1nm16L5dsOcyFu9a+CEhJndScYx47IHsmvGAqWW2ynppTyTnr47UNibsAvXuMllaJ7CcpQuLEzYGCZ/xnU4iqMJltvSlJ+/gFD9u1YqQ4es+YD9oZkWdSzuC6nkDlBEEqbZ5oy4qTSz+uqQyk/Ew0FZy5NUnZ8c8w4FSxKs8xPYmqZP8sPohdypb/Eo4s+Sto7yblxnj0YmzDK1B1P6EoHQsMpHGwNKlEwQDH9mnTP+HLEjomrl0lRli7sGPKolaY6DQarlswiLKY9R5r/f5IJN4WJTP2wma/8jnABRXMAxk/O+K0p2fd6HHAEyfvTjiFeziXnGJloviFef8LcmLDMo/krZxsmuktgG+WKosFk19wbTOu5bTWXCwF3tLnD5oHeVq1y0kbGHY9WHOlAMUCwshG++cOv7B0xWQvjSmSOCQk1BmejvBlQc6tU9okar0RfDxREfxziSCP18wydVutF2xjFc2PYg7CVjVtZc/NAPdPDQhSuqI+j0BLoft0zys0ma9HJxWZkArwUTuMw7dSI=

script:
  - grunt deploy