language: node_js

node_js:
- '0.12'

before_install:
- npm install -g grunt-cli

install:
- npm install
- npm test
- npm run build

script:
- grunt deploy

branches:
  only:
  - master

env:
  global:
    - secure: b3xg4aP+pDFj+sAC/kMH+oywOiifO09Xs99eSoqRK2cQZO0E2eE0kKUR++I3TnzylkbkK/nCgUY1EPTmutrOhga6bxUeRK1+ecx+Zv63iWXicDbD8eusCGAv6n3xNXK5e64H8toC7FvGzabYgbMCXeaAz9hCinPaXUNcDJOLARGXquwSRFtBHNrxwmnPNHng0FdC0De3lh2DRZnciGqVebydo1f0iouN2ibbqzyHW+erF0mJwhtj0E57Tdt+lZQHr04wWXu4671xCgVWjYKkRR4OAeBFpoWbVz80v3FcZ1tW63GhkHFo2YmQI2hCcuJd8/k+jAAlXwo8uYX2cVEhuiInBNS36f0PxMJMEFDt50ONa7u0e+BFa+HYnLGrmq3LwZHpTh9lSNd+8klmqEzYciWDkHQHo93rrQ1ZvXgGyeer0jTKWCCuiBu9KSVh0fiVJfFBPpFXGn+h9VxwFMOKDec2ZI0Bu3wVqynMsxLuOYrFnsyMcmihRmEcF8ApL6C3DXFe2JGE5e40H6MbFxrYyHM7DRNLltLFHYxXmFWLf7pUy5gx6yv5VP/q3UCemfTIUfFkBiHnZoW1IiX6kUgnbmnxmZFyIhnE/jDJpLV+FGgv6is2MSVmRhgQYHMciDxBG6mU8uyHKT98Ty41RupTcyzzN2DvT48Rzi3N5A3zdyY=
